#! /bin/sh

bspc monitor HDMI-1 -d 1 web game chat music 6 7 8 9 10
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
pgrep -x sxhkd > /dev/null || sxhkd &

flameshot &
dunst &
otd &
$HOME/.config/polybar/launch.sh
# picom --backend glx # kinda don't like compositing on X11
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Config

bspc config ignore_ewmh_struts true
bspc config border_width         3
bspc config window_gap           3
bspc config top_padding          30
bspc config normal_border_color "#44376a"
bspc config focused_border_color "#5D3FD3"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules

bspc rule -a osu!.exe desktop=^3
bspc rule -a discord desktop=^4
bspc rule -a firefox desktop=^2

# Extra

xsetroot -cursor_name left_ptr &
setxkbmap -model pc104 -layout gb,gb -variant dvorak,